# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/silvaa/Desktop/Lab 4/lab4/lab4.cache/wt} [current_project]
set_property parent.project_path {C:/Users/silvaa/Desktop/Lab 4/lab4/lab4.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/silvaa/Desktop/Lab 4/lab4/lab4.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/silvaa/Desktop/Lab 4/ALU.vhd}
  {C:/Users/silvaa/Desktop/Lab 4/datapath.vhd}
  {C:/Users/silvaa/Desktop/Lab 4/ffr.vhd}
  {C:/Users/silvaa/Desktop/Lab 4/fsm.vhd}
  {C:/Users/silvaa/Desktop/Lab 4/mux2to1.vhd}
  {C:/Users/silvaa/Desktop/Lab 4/mux4to1.vhd}
  {C:/Users/silvaa/Desktop/Lab 4/top.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
